<?php
// 消息配置文件
return array(
	'ADD_SUCCESS' => '添加成功了！',
	'ADD_ERROR' => '添加失败了，请稍后再试或者联系管理员！',
	'UPDATE_SUCCESS' => '修改成功了！',
	'UPDATE_ERROR' => '修改失败了，请稍后再试或者联系管理员！',
	'DELETE_SUCCESS' => '删除成功！',
	'DELETE_ERROR' => '删除失败了！请联系管理员',
	'LOGIN_ERROR' => '用户名或密码错误！',
	'OLD_PASSWORD_ERROR' => '原始密码错误！',
	'CHANGE_PWD_ERROR' => '修改密码失败，请联系管理员！',
	'CAPTCHA_ERROR' => '验证码错误！',
	'ACCOUNT_DISABLED' => '帐号已停用！',
	'LOGIN_SUCCESS' => '登录成功！',
	'SAVE_SUCCESS' => '保存成功！',
	'SAVE_ERROR' => '保存失败！',
	'CONTENT_ERROR' => '获取内容失败！',
	'TITLE_REQUIRE' => '请输入标题！',
	'PARAM_ERROR' => '参数错误！',
	'MOBILE_REPEAT' => '手机已经存在！',
	'MOBILE_ERROR' => '请输入手机号码！',
	'SUBMIT_SUCCESS' => '提交成功！',
	'SUBMIT_ERROR' => '提交失败了！请重试或者联系管理员！',
	'ADVISOR_ERROR' => '找不到这个投资顾问，请输入正确的名字！',
	'THX_OPINION' => '感谢您的真实意见,我们会更加完善服务质量！',
	'CUSTOMER_ERROR' => '此客户资料为空，请联系相关人员！',
	'CONTRACT_REPEAT' => '合同编号重复！',
	'RECORD_ERROR' => '此客户档案为空，请联系相关人员！',
	'RECORD_SHOP_ERROR' => '此商铺图纸为空，请联系相关人员！',
	'SHOP_REPEAT' => '此商铺图纸已经存在！',
	'CREATE_RECORD' => '请先创建客户档案！',
	'UPLOAD_SUCCESS' => '上传成功了！',
	'UPLOAD_ERROR' => '上传失败了，请稍后再试或者联系管理员！',
	'ADD_TRAINING_SUCCESS' => '课程添加成功，请选择地址或二维码发给相关人员！',
	'ADD_TRAINING_ERROR' => '添加失败请联系管理员！',
	'CUSTOMER_TIPS' => '请检查输入的业主姓名或者到档案查找正确业主姓名！',
	'SENDEE_ERROR' => '请选择接收人！',
	'COMPLAINT_ERROR' => '请选择被投诉人！',
	'EHR_ERROR' => 'EHR ERROR!',
);